ALTER TABLE users ADD COLUMN mfa_secret TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN mfa_confirmed BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN mfa_last_counter BIGINT NOT NULL DEFAULT -1;
